# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import status as module_0


def test_case_0():
    int_0 = 1407
    exit_status_0 = module_0.http_status_to_exit_status(int_0)
    assert exit_status_0 == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.SUCCESS == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.ERROR == module_0.ExitStatus.ERROR
    assert module_0.ExitStatus.ERROR_TIMEOUT == module_0.ExitStatus.ERROR_TIMEOUT
    assert module_0.ExitStatus.ERROR_HTTP_3XX == module_0.ExitStatus.ERROR_HTTP_3XX
    assert module_0.ExitStatus.ERROR_HTTP_4XX == module_0.ExitStatus.ERROR_HTTP_4XX
    assert module_0.ExitStatus.ERROR_HTTP_5XX == module_0.ExitStatus.ERROR_HTTP_5XX
    assert (
        module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
        == module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    )
    assert module_0.ExitStatus.PLUGIN_ERROR == module_0.ExitStatus.PLUGIN_ERROR
    assert module_0.ExitStatus.ERROR_CTRL_C == module_0.ExitStatus.ERROR_CTRL_C


def test_case_1():
    exit_status_0 = module_0.ExitStatus.ERROR_HTTP_5XX
    exit_status_1 = module_0.http_status_to_exit_status(exit_status_0)
    assert exit_status_1 == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.SUCCESS == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.ERROR == module_0.ExitStatus.ERROR
    assert module_0.ExitStatus.ERROR_TIMEOUT == module_0.ExitStatus.ERROR_TIMEOUT
    assert module_0.ExitStatus.ERROR_HTTP_3XX == module_0.ExitStatus.ERROR_HTTP_3XX
    assert module_0.ExitStatus.ERROR_HTTP_4XX == module_0.ExitStatus.ERROR_HTTP_4XX
    assert module_0.ExitStatus.ERROR_HTTP_5XX == module_0.ExitStatus.ERROR_HTTP_5XX
    assert (
        module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
        == module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    )
    assert module_0.ExitStatus.PLUGIN_ERROR == module_0.ExitStatus.PLUGIN_ERROR
    assert module_0.ExitStatus.ERROR_CTRL_C == module_0.ExitStatus.ERROR_CTRL_C


def test_case_2():
    exit_status_0 = module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    exit_status_1 = module_0.ExitStatus.ERROR_HTTP_5XX
    float_0 = 1833.200932
    exit_status_2 = module_0.ExitStatus.ERROR_HTTP_5XX
    exit_status_3 = module_0.http_status_to_exit_status(exit_status_1)
    assert exit_status_3 == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.SUCCESS == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.ERROR == module_0.ExitStatus.ERROR
    assert module_0.ExitStatus.ERROR_TIMEOUT == module_0.ExitStatus.ERROR_TIMEOUT
    assert module_0.ExitStatus.ERROR_HTTP_3XX == module_0.ExitStatus.ERROR_HTTP_3XX
    assert module_0.ExitStatus.ERROR_HTTP_4XX == module_0.ExitStatus.ERROR_HTTP_4XX
    assert module_0.ExitStatus.ERROR_HTTP_5XX == module_0.ExitStatus.ERROR_HTTP_5XX
    assert (
        module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
        == module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    )
    assert module_0.ExitStatus.PLUGIN_ERROR == module_0.ExitStatus.PLUGIN_ERROR
    assert module_0.ExitStatus.ERROR_CTRL_C == module_0.ExitStatus.ERROR_CTRL_C
    exit_status_4 = module_0.http_status_to_exit_status(float_0, float_0)
    assert exit_status_4 == module_0.ExitStatus.SUCCESS
    bool_0 = True
    exit_status_5 = module_0.http_status_to_exit_status(exit_status_0)
    assert exit_status_5 == module_0.ExitStatus.SUCCESS
    exit_status_6 = module_0.http_status_to_exit_status(bool_0)
    assert exit_status_6 == module_0.ExitStatus.SUCCESS
    int_0 = 19
    exit_status_7 = module_0.http_status_to_exit_status(int_0)
    assert exit_status_7 == module_0.ExitStatus.SUCCESS
    exit_status_8 = module_0.http_status_to_exit_status(exit_status_2)
    assert exit_status_8 == module_0.ExitStatus.SUCCESS
    exit_status_9 = module_0.ExitStatus.ERROR_HTTP_3XX
    int_1 = 311
    exit_status_10 = module_0.http_status_to_exit_status(int_1)
    assert exit_status_10 == module_0.ExitStatus.ERROR_HTTP_3XX
    exit_status_11 = module_0.http_status_to_exit_status(exit_status_9)
    assert exit_status_11 == module_0.ExitStatus.SUCCESS
    exit_status_12 = module_0.http_status_to_exit_status(exit_status_6)
    assert exit_status_12 == module_0.ExitStatus.SUCCESS


def test_case_3():
    int_0 = 542
    exit_status_0 = module_0.http_status_to_exit_status(int_0)
    assert exit_status_0 == module_0.ExitStatus.ERROR_HTTP_5XX
    assert module_0.ExitStatus.SUCCESS == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.ERROR == module_0.ExitStatus.ERROR
    assert module_0.ExitStatus.ERROR_TIMEOUT == module_0.ExitStatus.ERROR_TIMEOUT
    assert module_0.ExitStatus.ERROR_HTTP_3XX == module_0.ExitStatus.ERROR_HTTP_3XX
    assert module_0.ExitStatus.ERROR_HTTP_4XX == module_0.ExitStatus.ERROR_HTTP_4XX
    assert module_0.ExitStatus.ERROR_HTTP_5XX == module_0.ExitStatus.ERROR_HTTP_5XX
    assert (
        module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
        == module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    )
    assert module_0.ExitStatus.PLUGIN_ERROR == module_0.ExitStatus.PLUGIN_ERROR
    assert module_0.ExitStatus.ERROR_CTRL_C == module_0.ExitStatus.ERROR_CTRL_C


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    exit_status_0 = module_0.http_status_to_exit_status(bool_0)
    assert exit_status_0 == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.SUCCESS == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.ERROR == module_0.ExitStatus.ERROR
    assert module_0.ExitStatus.ERROR_TIMEOUT == module_0.ExitStatus.ERROR_TIMEOUT
    assert module_0.ExitStatus.ERROR_HTTP_3XX == module_0.ExitStatus.ERROR_HTTP_3XX
    assert module_0.ExitStatus.ERROR_HTTP_4XX == module_0.ExitStatus.ERROR_HTTP_4XX
    assert module_0.ExitStatus.ERROR_HTTP_5XX == module_0.ExitStatus.ERROR_HTTP_5XX
    assert (
        module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
        == module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    )
    assert module_0.ExitStatus.PLUGIN_ERROR == module_0.ExitStatus.PLUGIN_ERROR
    assert module_0.ExitStatus.ERROR_CTRL_C == module_0.ExitStatus.ERROR_CTRL_C
    float_0 = 1833.200932
    exit_status_1 = module_0.ExitStatus.ERROR_CTRL_C
    exit_status_2 = module_0.http_status_to_exit_status(exit_status_1)
    assert exit_status_2 == module_0.ExitStatus.SUCCESS
    exit_status_3 = module_0.http_status_to_exit_status(float_0, float_0)
    assert exit_status_3 == module_0.ExitStatus.SUCCESS
    bool_1 = True
    exit_status_4 = module_0.http_status_to_exit_status(bool_1)
    assert exit_status_4 == module_0.ExitStatus.SUCCESS
    exit_status_5 = module_0.http_status_to_exit_status(exit_status_4, exit_status_3)
    assert exit_status_5 == module_0.ExitStatus.SUCCESS
    exit_status_6 = module_0.ExitStatus.SUCCESS
    exit_status_7 = module_0.http_status_to_exit_status(exit_status_0, exit_status_6)
    assert exit_status_7 == module_0.ExitStatus.SUCCESS
    exit_status_8 = module_0.http_status_to_exit_status(exit_status_4)
    assert exit_status_8 == module_0.ExitStatus.SUCCESS
    exit_status_9 = module_0.http_status_to_exit_status(exit_status_4)
    assert exit_status_9 == module_0.ExitStatus.SUCCESS
    exit_status_10 = module_0.http_status_to_exit_status(float_0)
    assert exit_status_10 == module_0.ExitStatus.SUCCESS
    exit_status_11 = module_0.http_status_to_exit_status(exit_status_5)
    assert exit_status_11 == module_0.ExitStatus.SUCCESS
    int_0 = 455
    exit_status_12 = module_0.http_status_to_exit_status(int_0)
    assert exit_status_12 == module_0.ExitStatus.ERROR_HTTP_4XX
    exit_status_13 = module_0.http_status_to_exit_status(exit_status_3)
    assert exit_status_13 == module_0.ExitStatus.SUCCESS
    none_type_0 = None
    module_0.http_status_to_exit_status(none_type_0)


def test_case_5():
    bool_0 = False
    exit_status_0 = module_0.http_status_to_exit_status(bool_0)
    assert exit_status_0 == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.SUCCESS == module_0.ExitStatus.SUCCESS
    assert module_0.ExitStatus.ERROR == module_0.ExitStatus.ERROR
    assert module_0.ExitStatus.ERROR_TIMEOUT == module_0.ExitStatus.ERROR_TIMEOUT
    assert module_0.ExitStatus.ERROR_HTTP_3XX == module_0.ExitStatus.ERROR_HTTP_3XX
    assert module_0.ExitStatus.ERROR_HTTP_4XX == module_0.ExitStatus.ERROR_HTTP_4XX
    assert module_0.ExitStatus.ERROR_HTTP_5XX == module_0.ExitStatus.ERROR_HTTP_5XX
    assert (
        module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
        == module_0.ExitStatus.ERROR_TOO_MANY_REDIRECTS
    )
    assert module_0.ExitStatus.PLUGIN_ERROR == module_0.ExitStatus.PLUGIN_ERROR
    assert module_0.ExitStatus.ERROR_CTRL_C == module_0.ExitStatus.ERROR_CTRL_C
    float_0 = 1833.200932
    exit_status_1 = module_0.ExitStatus.ERROR_CTRL_C
    exit_status_2 = module_0.http_status_to_exit_status(exit_status_1)
    assert exit_status_2 == module_0.ExitStatus.SUCCESS
    exit_status_3 = module_0.http_status_to_exit_status(float_0, float_0)
    assert exit_status_3 == module_0.ExitStatus.SUCCESS
    exit_status_4 = module_0.http_status_to_exit_status(bool_0)
    assert exit_status_4 == module_0.ExitStatus.SUCCESS
    exit_status_5 = module_0.ExitStatus.SUCCESS
    exit_status_6 = module_0.http_status_to_exit_status(exit_status_0, exit_status_5)
    assert exit_status_6 == module_0.ExitStatus.SUCCESS
    exit_status_7 = module_0.http_status_to_exit_status(exit_status_4)
    assert exit_status_7 == module_0.ExitStatus.SUCCESS
    exit_status_8 = module_0.http_status_to_exit_status(exit_status_3)
    assert exit_status_8 == module_0.ExitStatus.SUCCESS
    exit_status_9 = module_0.http_status_to_exit_status(float_0)
    assert exit_status_9 == module_0.ExitStatus.SUCCESS
    int_0 = 19
    exit_status_10 = module_0.http_status_to_exit_status(int_0)
    assert exit_status_10 == module_0.ExitStatus.SUCCESS
    int_1 = 399
    int_2 = 710
    exit_status_11 = module_0.http_status_to_exit_status(int_1, int_2)
    assert exit_status_11 == module_0.ExitStatus.SUCCESS
    int_3 = -3265
    exit_status_12 = module_0.http_status_to_exit_status(int_3)
    assert exit_status_12 == module_0.ExitStatus.SUCCESS
    int_4 = -1069
    exit_status_13 = module_0.http_status_to_exit_status(int_4)
    assert exit_status_13 == module_0.ExitStatus.SUCCESS
    int_5 = 487
    exit_status_14 = module_0.http_status_to_exit_status(int_5)
    assert exit_status_14 == module_0.ExitStatus.ERROR_HTTP_4XX
