# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import builtins as module_0
import dummy as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    object_0 = module_0.object()
    list_0 = [object_0, object_0, object_0, object_0]
    module_1.Dummy(*list_0, **list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    dummy_0 = module_1.Dummy()
    assert f"{type(dummy_0).__module__}.{type(dummy_0).__qualname__}" == "dummy.Dummy"
    str_0 = "B"
    dummy_0.add(str_0, dummy_0)
